-- ============================================================
-- Sediment — Seed Data (development only)
-- ============================================================

INSERT INTO subreddits (id, name, total_diggers)
VALUES ('00000000-0000-0000-0000-000000000001', 'r/history', 8742)
ON CONFLICT DO NOTHING;

INSERT INTO seasons (id, name, civilization_theme, starts_at, ends_at, pass_tier_max)
VALUES (
  '00000000-0000-0000-0000-000000000010',
  'The Lost Empire',
  'Desert Empire',
  now() - interval '10 days',
  now() + interval '32 days',
  25
)
ON CONFLICT DO NOTHING;

INSERT INTO civilizations (id, subreddit_id, season_id, name, origin_story)
VALUES (
  '00000000-0000-0000-0000-000000000020',
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000010',
  'The Sun Priests of Kalveth',
  'Generated by AI: a desert empire that rose around a sunken courtyard oasis, ruled by an order of Sun Priests until an unexplained collapse.'
)
ON CONFLICT DO NOTHING;

INSERT INTO dig_layers (id, subreddit_id, index, name, progress, chamber_type, is_rare_chamber)
VALUES (
  '00000000-0000-0000-0000-000000000030',
  '00000000-0000-0000-0000-000000000001',
  7,
  'The Sunken Courtyard',
  63,
  'ruins',
  false
)
ON CONFLICT DO NOTHING;

INSERT INTO community_events (subreddit_id, type, title, description, starts_at, ends_at, progress, goal)
VALUES
  (
    '00000000-0000-0000-0000-000000000001',
    'double_restoration_weekend',
    'Global Event: Double Restoration Weekend!',
    'All restoration XP is doubled.',
    now(),
    now() + interval '28 hours',
    NULL,
    NULL
  ),
  (
    '00000000-0000-0000-0000-000000000001',
    'legendary_discovery_hunt',
    'Legendary Discovery Hunt — Find the Sun King''s Tomb',
    'Community-wide excavation goal.',
    now(),
    now() + interval '42 hours',
    72,
    100
  )
ON CONFLICT DO NOTHING;
